Init repo
sameedmohsin28/Awesome-Books-ES6-Syntax pull request #1
Opened 2023-03-01 03:19 UTC by sameedmohsin28

2023-03-01 04:12 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi @sameedmohsin28 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif"/>

## Highlights 🎯 
✔️ Used ES6 syntax 📌 
✔️ Used modules 📌 
✔️ Used GitHub Flow
✔️ Good commit history
✔️ No inter errors

## Required Changes ♻️
_Check the comments under the review._

- [ ] The entire app is not working; I am unable to add or remove books from the list, and the navigation is not responding as well. Please try to fix this issue 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-01 04:12 UTC, codepantha commented on index.html
> +            </div>
- [ ] According to the project requirements, the current date should be displayed right below the navigation bar. Please implement this feature using the [Luxon](https://github.com/moment/luxon/blob/master/docs/install.md) library
![image](https://user-images.githubusercontent.com/46839548/222042112-9c09160d-bc3a-414b-9fc3-5080a93ce6f6.png)

2023-03-01 04:29 UTC, sameedmohsin28 commented on index.html
> +            </div>
Hi,

I have displayed the date right below the navigation bar just as mentioned in the project requirements. Could you please specify the problem due to which it doesn't show on your end? Maybe try using VSCode Live Server Extension to counter this problem.
![image](https://user-images.githubusercontent.com/122236545/222043955-b5c9a7ef-861b-4f80-bf0c-f7ccdf600c76.png)
![image](https://user-images.githubusercontent.com/122236545/222044215-e7ea36f1-6961-4dc1-8e11-3aa36c5c3700.png)
![image](https://user-images.githubusercontent.com/122236545/222044782-6b04bbef-8e73-4952-93df-e9d191d5305a.png)

2023-03-02 06:12 UTC, sameedmohsin28 commented on index.html
> +            </div>
Hi @codepantha,

This is a reminder in case you missed the notification about my reply to your review. Kindly see my reply and suggest what could be done.

Thanks.

2023-03-04 13:28 UTC, Nemwel-Boniface reviewed
## Hello @sameedmohsin28   👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

I have inspected your project locally and the following mentioned changes by @codepantha  seem to be working perfectly fine. 
1. I am able to navigate from different pages without a hitch. I am also able to add and delete a book.

[Screencast from 04-03-2023 04:25:41 ALASIRI.webm](https://user-images.githubusercontent.com/86318284/222904406-9c67ec9d-97e9-4a07-a4bb-a790a2e2e0ce.webm)


2. The date and time is being shown below the navbar correctly.

![image](https://user-images.githubusercontent.com/86318284/222904371-89cff739-d06d-4082-a8bb-1dac84be3f7e.png)


Because the requested changes were of features which were already implemented, I think your project can be approved.


Kindly submit your project in your dashboard and the next reviewer will approve it immediately :rocket: 


In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!

2023-03-04 21:10 UTC, andersonlebon approved these changes
## Hi @sameedmohsin28 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-06 15:18 UTC, omarsalem7 commented
Hi @sameedmohsin28 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights

✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-15 08:20 UTC, merged